// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM-8vmUDD2T589uZc8psMJ9hoepSvaqFY',
    appId: '1:780291908315:web:b93ebd99d893e4212c62fe',
    messagingSenderId: '780291908315',
    projectId: 'shankara-card',
    authDomain: 'shankara-card.firebaseapp.com',
    storageBucket: 'shankara-card.appspot.com',
    measurementId: 'G-6ZYKF9HB1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBY6sPriMdsWCLJQZpEMZRhYoQWX6xdgo',
    appId: '1:780291908315:android:d392dd109bcc4eed2c62fe',
    messagingSenderId: '780291908315',
    projectId: 'shankara-card',
    storageBucket: 'shankara-card.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATUuzEiTAHl7OYAfCwyROIOXzHlcw7JKc',
    appId: '1:780291908315:ios:7cec9e3cb05a24a92c62fe',
    messagingSenderId: '780291908315',
    projectId: 'shankara-card',
    storageBucket: 'shankara-card.appspot.com',
    iosClientId: '780291908315-7m3gspmlo4to118ol9pvkr7qfqhc8q5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.shankaraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATUuzEiTAHl7OYAfCwyROIOXzHlcw7JKc',
    appId: '1:780291908315:ios:7cec9e3cb05a24a92c62fe',
    messagingSenderId: '780291908315',
    projectId: 'shankara-card',
    storageBucket: 'shankara-card.appspot.com',
    iosClientId: '780291908315-7m3gspmlo4to118ol9pvkr7qfqhc8q5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.shankaraApp',
  );
}
